STUDY_NAME : "exp82"

#BUCKET_NAME: "resultados"

BUCKET_NAME: "/home/rami_santamaria92/buckets/b1"

competencia01:
    DATA_PATH: "/home/rami_santamaria92/datasets/competencia_02_crudo.csv.gz"
    DATA_PATH_LOCAL: "data/competencia_01_crudo.csv"
    SEMILLA: [143287, 146213, 310111, 670627, 880553]
    SEMILLERO: [100003,  140009,  180023,  220009,  260003, 300007,  340027,  380041,  420047,  460051, 500057,  540061,  580079,  620087,  660097, 700099,  740099,  780119,  820129,  860143, 900149,  940157,  980159,  980179,  999983]
    MES_TRAIN: [202007, 202008, 202009, 202010, 202011, 202012,202101,202102] # LE FALTAN MESES. APARTE DE ESTOS 201901, 201902, 201903, 201904, 201906, 201907, 201908, 201909, 201911, 201912,202001, 202002, 202003, 202004, 202005,
    MES_VALIDACION: [202104]
    MES_TEST: [202106]
    MES_PREDIC: [202108]
    INICIO_ENVIOS: 5000
    FIN_ENVIOS: 25000
    PASO_ENVIOS: 500
    GANANCIA_ACIERTO: 78
    COSTO_ESTIMULO: -2
    UNDERSUMPLING: 0.1
    